batch_size: 128
checkpoint_path: lightning_logs\version_48\best_checkpoint.ckpt
config: configs\massSpringchain.yaml
context_length: 20
data_samples: 5000
dataset: custom:massspringchain
device: cuda:0
diffusion_config: diffusion_s4
dt: 0.1
eval_every: 50
freq: H
gradient_clip_val: 0.5
init_skip: true
lr: 0.001
max_epochs: 250
num_batches_per_epoch: 100
num_samples: 16
observation_dim: 3
out_dir: ./
prediction_length: 5
q: 0
r: 0
setup: forecasting
use_transformer: false
